kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
spec:
  type: NodePort
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31080
